# Check out https://docs.codemagic.io/getting-started/building-an-ionic-app/ for more information
# Please review and update values in curly braces
# Remove or comment out the workflows you don't require

#workflows:
    # Ionic Capacitor workflows
    # ionic-capacitor-ios-app:
    #     name: Ionic App
    #     environment:
    #         vars:
    #             XCODE_WORKSPACE: "ios/App/IonicApp.xcworkspace" # <- 'IonicApp' is the default workspace name for Capacitor projects
    #             XCODE_SCHEME: "IonicApp" # <- 'IonicApp' is the default Scheme name for Capacitor projects
    #         node: latest
    #     scripts:
    #         - npm install     
    #         - npx cap sync
    #         - |
    #             # build iOS
    #             cd platforms/ios
    #             pod install
    #             xcodebuild build -workspace "$XCODE_WORKSPACE" -scheme "$XCODE_SCHEME" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO CODE_SIGNING_ALLOWED=NO                
    #     artifacts:
    #         - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.app
    #         - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.dSYM
    # ionic-capacitor-android-app:
    #     name: Ionic App
    #     environment:
    #         node: latest
    #     scripts:
    #         - npm install     
    #         - npm cap sync
    #         - |
    #             # build Android
    #             cd android
    #             ./gradlew assembleDebug                
    #     artifacts:
    #         - android/app/build/outputs/**/*.apk
    # Ionic Cordova workflows
    # ionic-cordova-ios-app:
    #     name: Ionic Cordova iOS App
    #     environment:
    #         vars:
    #             XCODE_WORKSPACE: "{{ ADD WORKSPACE NAME HERE }}"
    #             XCODE_SCHEME: "{{ ADD SCHEME NAME HERE }}"
    #         node: latest
    #     scripts: 
    #         - |
    #             # install dependencies and update to Cordova version 9
    #             npm install
    #             cvm install 9.0.0
    #             cvm use 9.0.0                
    #         - |
    #             # Setup Cordova iOS platform
    #             ionic cordova platform remove ios --nosave
    #             ionic cordova platform add ios --confirm --no-interactive --noresources                
    #         - |
    #             # build iOS
    #             cd platforms/ios
    #             pod install
    #             xcodebuild build -workspace "$XCODE_WORKSPACE" -scheme "$XCODE_SCHEME" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO CODE_SIGNING_ALLOWED=NO                
    #     artifacts:
    #         - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.app
    #         - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.dSYM
    # ionic-cordova-android-app:
    #     name: Ionic Cordova Android App
    #     environment:
    #         node: latest
        # scripts: 
        #     - |
        #         npm install
        #         cvm install 9.0.0
        #         cvm use 9.0.0                
        #     - |
                
        #         ionic cordova platform remove android --nosave
        #         ionic cordova platform add android --confirm --no-interactive --noresources                
        #     - |
                
        #         script: ionic cordova build android --debug --no-interactive --device                
        # artifacts:
        #     - platforms/android/app/build/outputs/**/*.apk

workflows:
android-workflow:
name: Ionic-Android-Cordova
scripts:
    - name: Install npm dependencies and update Cordova version
      script: | 
        npm install
        npm ci # equivalent of npm install for CI systems.
               # Requires package-lock.json or npm-shrinkwrap.json to be present
        cvm install 9.0.0
        cvm use 9.0.0 
    - name: Setup Cordova Android platform
      script: | 
        ionic cordova platform remove android --nosave
        ionic cordova platform add android \
          --confirm \
          --no-interactive \
          --noresources 
    - name: Build Android Cordova App
      script: | 
        ionic cordova build android \
          --release \
          --no-interactive \
          --prod \
          --device
    - name: Sign APK
      script: | 
        APK_PATH=$(find platforms/android/app/build/outputs/apk/release -name "*.apk" | head -1)
        jarsigner \
          -sigalg SHA1withRSA \
          -digestalg SHA1 \
          -keystore $CM_KEYSTORE_PATH \
          -storepass $CM_KEYSTORE_PASSWORD \
          -keypass $CM_KEY_PASSWORD \
          $APK_PATH $CM_KEY_ALIAS         
artifacts:
    - platforms/android/app/build/outputs/**/*.apk
publishing:
    email:
       recipients:
            - veeramani.karthick@fourbends.com
       notify:
        success: true
        failure: false